import { NextRequest } from "next/server";
import { store } from "@/lib/store";
import type { Lead } from "@/lib/types";

export async function GET(request: NextRequest) {
  const icpId = request.nextUrl.searchParams.get("icp_id");
  const format = request.nextUrl.searchParams.get("format") || "csv";

  if (!icpId) {
    return Response.json({ error: "icp_id required" }, { status: 400 });
  }

  const leads = (await store.leads.getByICP(icpId)).sort((a, b) => b.score - a.score);

  if (leads.length === 0) {
    return Response.json({ error: "No leads found" }, { status: 404 });
  }

  if (format === "hubspot") {
    return hubspotCSV(leads);
  }

  if (format === "summary") {
    return await summaryReport(leads);
  }

  return standardCSV(leads);
}

function standardCSV(leads: Lead[]): Response {
  const headers = [
    "Company Name", "Website", "Score", "Data Quality", "Completeness %",
    "Summary", "Emails", "Phones", "Hiring Signals", "Reason", "Outreach Angle", "Status",
  ];

  const rows = leads.map((l) => [
    l.company_name,
    l.website,
    l.score.toString(),
    l.data_quality,
    l.completeness.toString(),
    l.enrichment?.summary || "unknown",
    l.enrichment?.emails.map((e) => e.email).join("; ") || "",
    l.enrichment?.phones.join("; ") || "",
    l.enrichment?.hiring_signals.join("; ") || "",
    l.llm_reason || "",
    l.outreach_angle || "",
    l.status,
  ]);

  const csv = [headers, ...rows]
    .map((row) => row.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(","))
    .join("\n");

  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv",
      "Content-Disposition": 'attachment; filename="leads-export.csv"',
    },
  });
}

function hubspotCSV(leads: Lead[]): Response {
  const headers = [
    "Company name", "Company Domain Name", "Phone Number",
    "Number of Employees", "Description", "Lead Status",
    "Email", "Score",
  ];

  const rows = leads.map((l) => [
    l.company_name,
    l.domain,
    l.enrichment?.phones[0] || "",
    l.enrichment?.size_signals[0] || "",
    l.enrichment?.summary || "",
    l.status === "good" ? "OPEN" : l.status === "contacted" ? "IN_PROGRESS" : "NEW",
    l.enrichment?.emails[0]?.email || l.contact_email || "",
    l.score.toString(),
  ]);

  const csv = [headers, ...rows]
    .map((row) => row.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(","))
    .join("\n");

  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv",
      "Content-Disposition": 'attachment; filename="leads-hubspot.csv"',
    },
  });
}

async function summaryReport(leads: Lead[]): Promise<Response> {
  const top10 = leads.slice(0, 10);
  const icp = await store.icp.get(leads[0]?.icp_id || "");

  let report = `# Smart Lead Ranker — Top 10 Lead Summary\n\n`;
  report += `**Generated:** ${new Date().toLocaleDateString()}\n`;
  report += `**Total leads analyzed:** ${leads.length}\n`;

  if (icp) {
    report += `**Target profile:** ${icp.name}\n`;
    report += `**Keywords:** ${icp.industry_keywords.join(", ")}\n`;
    report += `**Region:** ${icp.region}\n\n`;
  }

  report += `---\n\n`;

  top10.forEach((lead, i) => {
    report += `## ${i + 1}. ${lead.company_name} (Score: ${lead.score}/100)\n\n`;
    report += `- **Website:** ${lead.website}\n`;
    report += `- **Data Quality:** ${lead.data_quality} (${lead.completeness}% complete)\n`;
    report += `- **Summary:** ${lead.enrichment?.summary || "unknown"}\n`;

    if (lead.enrichment?.emails.length) {
      report += `- **Contact Emails:** ${lead.enrichment.emails.map((e) => e.email).join(", ")}\n`;
    }
    if (lead.enrichment?.hiring_signals.length) {
      report += `- **Hiring Signals:** ${lead.enrichment.hiring_signals.join(", ")}\n`;
    }

    report += `- **Why this lead:** ${lead.llm_reason || "N/A"}\n`;
    report += `- **Outreach angle:** ${lead.outreach_angle || "N/A"}\n`;

    if (lead.enrichment?.source_urls.length) {
      report += `- **Sources:** ${lead.enrichment.source_urls.join(", ")}\n`;
    }

    report += `\n`;
  });

  report += `---\n\n*Report generated by Smart Lead Ranker. All data sourced from publicly available information.*\n`;

  return new Response(report, {
    headers: {
      "Content-Type": "text/markdown",
      "Content-Disposition": 'attachment; filename="top-10-leads-report.md"',
    },
  });
}
